
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T> = DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>> & T

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }> & T

interface _GlobalComponents {
  'AppFooter': typeof import("../../components/AppFooter.vue").default
  'AppHeader': typeof import("../../components/AppHeader.vue").default
  'AtomsActionButton': typeof import("../../components/Atoms/ActionButton.vue").default
  'AtomsActionButtonD': typeof import("../../components/Atoms/ActionButtonD.vue").default
  'AtomsActionButtonn': typeof import("../../components/Atoms/ActionButtonn.vue").default
  'AtomsActionLinkButton': typeof import("../../components/Atoms/ActionLinkButton.vue").default
  'AtomsAddToCartButton': typeof import("../../components/Atoms/AddToCartButton.vue").default
  'AtomsAppLogo': typeof import("../../components/Atoms/AppLogo.vue").default
  'AtomsBaseIcon': typeof import("../../components/Atoms/BaseIcon.vue").default
  'AtomsBaseInput': typeof import("../../components/Atoms/BaseInput.vue").default
  'AtomsButtonEtsy': typeof import("../../components/Atoms/ButtonEtsy.vue").default
  'AtomsDividerLine': typeof import("../../components/Atoms/DividerLine.vue").default
  'AtomsFormSelect': typeof import("../../components/Atoms/FormSelect.vue").default
  'AtomsHeaderButton': typeof import("../../components/Atoms/HeaderButton.vue").default
  'AtomsHeading': typeof import("../../components/Atoms/Heading.vue").default
  'AtomsHeadingAdd': typeof import("../../components/Atoms/HeadingAdd.vue").default
  'AtomsHeadingD': typeof import("../../components/Atoms/HeadingD.vue").default
  'AtomsHeadingH': typeof import("../../components/Atoms/HeadingH.vue").default
  'AtomsImage': typeof import("../../components/Atoms/Image.vue").default
  'AtomsImageAtom': typeof import("../../components/Atoms/ImageAtom.vue").default
  'AtomsImageAtomD': typeof import("../../components/Atoms/ImageAtomD.vue").default
  'AtomsImageAtomH': typeof import("../../components/Atoms/ImageAtomH.vue").default
  'AtomsImageAtomm': typeof import("../../components/Atoms/ImageAtomm.vue").default
  'AtomsInputCheckbox': typeof import("../../components/Atoms/InputCheckbox.vue").default
  'AtomsInputEmail': typeof import("../../components/Atoms/InputEmail.vue").default
  'AtomsLabelApp': typeof import("../../components/Atoms/LabelApp.vue").default
  'AtomsLabelLinkH': typeof import("../../components/Atoms/LabelLinkH.vue").default
  'AtomsLinkMail': typeof import("../../components/Atoms/LinkMail.vue").default
  'AtomsNavLink': typeof import("../../components/Atoms/NavLink.vue").default
  'AtomsParagraphAdd': typeof import("../../components/Atoms/ParagraphAdd.vue").default
  'AtomsParagraphD': typeof import("../../components/Atoms/ParagraphD.vue").default
  'AtomsParagraphH': typeof import("../../components/Atoms/ParagraphH.vue").default
  'AtomsPaymentCircle': typeof import("../../components/Atoms/PaymentCircle.vue").default
  'AtomsPriceLabel': typeof import("../../components/Atoms/PriceLabel.vue").default
  'AtomsPrimaryButton': typeof import("../../components/Atoms/PrimaryButton.vue").default
  'AtomsPrimaryButtonn': typeof import("../../components/Atoms/PrimaryButtonn.vue").default
  'AtomsProductImage': typeof import("../../components/Atoms/ProductImage.vue").default
  'AtomsSearchInput': typeof import("../../components/Atoms/SearchInput.vue").default
  'AtomsSectionTitle': typeof import("../../components/Atoms/SectionTitle.vue").default
  'AtomsSocialIcon': typeof import("../../components/Atoms/SocialIcon.vue").default
  'AtomsSocialImage': typeof import("../../components/Atoms/SocialImage.vue").default
  'AtomsSocialImagee': typeof import("../../components/Atoms/SocialImagee.vue").default
  'AtomsSpacerAdd': typeof import("../../components/Atoms/SpacerAdd.vue").default
  'AtomsTextInputArea': typeof import("../../components/Atoms/TextInputArea.vue").default
  'AtomsLogoMail': typeof import("../../components/Atoms/logoMail.vue").default
  'HolidayCategoryGridView': typeof import("../../components/HolidayCategoryGridView.vue").default
  'HolidayGiftSlider': typeof import("../../components/HolidayGiftSlider.vue").default
  'HomePageCampaignsSection': typeof import("../../components/HomePageCampaignsSection.vue").default
  'MoleculesAppDownloadSection': typeof import("../../components/Molecules/AppDownloadSection.vue").default
  'MoleculesCampaignCard': typeof import("../../components/Molecules/CampaignCard.vue").default
  'MoleculesCardInfo': typeof import("../../components/Molecules/CardInfo.vue").default
  'MoleculesCategoryBox': typeof import("../../components/Molecules/CategoryBox.vue").default
  'MoleculesCategoryCard': typeof import("../../components/Molecules/CategoryCard.vue").default
  'MoleculesCouponSection': typeof import("../../components/Molecules/CouponSection.vue").default
  'MoleculesDealBanner': typeof import("../../components/Molecules/DealBanner.vue").default
  'MoleculesHousewarmingBanner': typeof import("../../components/Molecules/HousewarmingBanner.vue").default
  'MoleculesHubTitleArea': typeof import("../../components/Molecules/HubTitleArea.vue").default
  'MoleculesInputGroup': typeof import("../../components/Molecules/InputGroup.vue").default
  'MoleculesInputGroupp': typeof import("../../components/Molecules/InputGroupp.vue").default
  'MoleculesItemDetailRow': typeof import("../../components/Molecules/ItemDetailRow.vue").default
  'MoleculesLinkColumn': typeof import("../../components/Molecules/LinkColumn.vue").default
  'MoleculesNavLinkItem': typeof import("../../components/Molecules/NavLinkItem.vue").default
  'MoleculesOptionGroup': typeof import("../../components/Molecules/OptionGroup.vue").default
  'MoleculesOptionsRow': typeof import("../../components/Molecules/OptionsRow.vue").default
  'MoleculesPaymentMethod': typeof import("../../components/Molecules/PaymentMethod.vue").default
  'MoleculesPersonalization': typeof import("../../components/Molecules/Personalization.vue").default
  'MoleculesPriceSection': typeof import("../../components/Molecules/PriceSection.vue").default
  'MoleculesProductCard': typeof import("../../components/Molecules/ProductCard.vue").default
  'MoleculesProductCardd': typeof import("../../components/Molecules/ProductCardd.vue").default
  'MoleculesRenewableMessage': typeof import("../../components/Molecules/RenewableMessage.vue").default
  'MoleculesSearchBar': typeof import("../../components/Molecules/SearchBar.vue").default
  'MoleculesSellerBadge': typeof import("../../components/Molecules/SellerBadge.vue").default
  'MoleculesSellerInfoRow': typeof import("../../components/Molecules/SellerInfoRow.vue").default
  'MoleculesSellerRow': typeof import("../../components/Molecules/SellerRow.vue").default
  'MoleculesSocialButton': typeof import("../../components/Molecules/SocialButton.vue").default
  'MoleculesSocialButtonn': typeof import("../../components/Molecules/SocialButtonn.vue").default
  'MoleculesSocialIcons': typeof import("../../components/Molecules/SocialIcons.vue").default
  'MoleculesStaticHeader': typeof import("../../components/Molecules/StaticHeader.vue").default
  'MoleculesSubscribeForm': typeof import("../../components/Molecules/SubscribeForm.vue").default
  'MoleculesThumbnailItem': typeof import("../../components/Molecules/ThumbnailItem.vue").default
  'MoleculesUserActions': typeof import("../../components/Molecules/UserActions.vue").default
  'OrganismAuthModal': typeof import("../../components/Organism/AuthModal.vue").default
  'OrganismBigDeals': typeof import("../../components/Organism/BigDeals.vue").default
  'OrganismCampaignGridSection': typeof import("../../components/Organism/CampaignGridSection.vue").default
  'OrganismCartFooter': typeof import("../../components/Organism/CartFooter.vue").default
  'OrganismCartItemDetails': typeof import("../../components/Organism/CartItemDetails.vue").default
  'OrganismCategoryGrid': typeof import("../../components/Organism/CategoryGrid.vue").default
  'OrganismCategoryMenu': typeof import("../../components/Organism/CategoryMenu.vue").default
  'OrganismCategorySliderSection': typeof import("../../components/Organism/CategorySliderSection.vue").default
  'OrganismCheckoutModal': typeof import("../../components/Organism/CheckoutModal.vue").default
  'OrganismCustomizableIdeas': typeof import("../../components/Organism/CustomizableIdeas.vue").default
  'OrganismDaintySparkle': typeof import("../../components/Organism/DaintySparkle.vue").default
  'OrganismDayDeals': typeof import("../../components/Organism/DayDeals.vue").default
  'OrganismEnchantedGarden': typeof import("../../components/Organism/EnchantedGarden.vue").default
  'OrganismFilterRow': typeof import("../../components/Organism/FilterRow.vue").default
  'OrganismFilterSidebar': typeof import("../../components/Organism/FilterSidebar.vue").default
  'OrganismHighOctaneStyle': typeof import("../../components/Organism/HighOctaneStyle.vue").default
  'OrganismHolidayFinds': typeof import("../../components/Organism/HolidayFinds.vue").default
  'OrganismHubHeader': typeof import("../../components/Organism/HubHeader.vue").default
  'OrganismImageGallery': typeof import("../../components/Organism/ImageGallery.vue").default
  'OrganismInspiredPicks': typeof import("../../components/Organism/InspiredPicks.vue").default
  'OrganismItemDetails': typeof import("../../components/Organism/ItemDetails.vue").default
  'OrganismJumpBackIn': typeof import("../../components/Organism/JumpBackIn.vue").default
  'OrganismLoginForm': typeof import("../../components/Organism/LoginForm.vue").default
  'OrganismMainFooter': typeof import("../../components/Organism/MainFooter.vue").default
  'OrganismMeetYourSeller': typeof import("../../components/Organism/MeetYourSeller.vue").default
  'OrganismNavigationLinks': typeof import("../../components/Organism/NavigationLinks.vue").default
  'OrganismPaymentSummary': typeof import("../../components/Organism/PaymentSummary.vue").default
  'OrganismProductActions': typeof import("../../components/Organism/ProductActions.vue").default
  'OrganismProductSlider': typeof import("../../components/Organism/ProductSlider.vue").default
  'OrganismProductSliderSection': typeof import("../../components/Organism/ProductSliderSection.vue").default
  'OrganismRecentFinds': typeof import("../../components/Organism/RecentFinds.vue").default
  'OrganismRegisterFormm': typeof import("../../components/Organism/RegisterFormm.vue").default
  'OrganismRelatedSearches': typeof import("../../components/Organism/RelatedSearches.vue").default
  'OrganismReviewsSection': typeof import("../../components/Organism/ReviewsSection.vue").default
  'OrganismShippingPolicies': typeof import("../../components/Organism/ShippingPolicies.vue").default
  'OrganismSideCartDrawer': typeof import("../../components/Organism/SideCartDrawer.vue").default
  'OrganismSimilarProductsSection': typeof import("../../components/Organism/SimilarProductsSection.vue").default
  'OrganismSpecialGifts': typeof import("../../components/Organism/SpecialGifts.vue").default
  'OrganismStockingStuffers': typeof import("../../components/Organism/StockingStuffers.vue").default
  'OrganismSubscriptionSection': typeof import("../../components/Organism/SubscriptionSection.vue").default
  'OrganismTopBannerSection': typeof import("../../components/Organism/TopBannerSection.vue").default
  'OrganismTopHeaderRow': typeof import("../../components/Organism/TopHeaderRow.vue").default
  'ProductDetailView': typeof import("../../components/ProductDetailView.vue").default
  'RelatedProductSlider': typeof import("../../components/RelatedProductSlider.vue").default
  'ShoppingCart': typeof import("../../components/ShoppingCart.vue").default
  'UserLoginForm': typeof import("../../components/UserLoginForm.vue").default
  'UserRegisterForm': typeof import("../../components/UserRegisterForm.vue").default
  'IconsIconCommunity': typeof import("../../components/icons/IconCommunity.vue").default
  'IconsIconDocumentation': typeof import("../../components/icons/IconDocumentation.vue").default
  'IconsIconEcosystem': typeof import("../../components/icons/IconEcosystem.vue").default
  'IconsIconSupport': typeof import("../../components/icons/IconSupport.vue").default
  'IconsIconTooling': typeof import("../../components/icons/IconTooling.vue").default
  'NuxtWelcome': typeof import("../../node_modules/nuxt/dist/app/components/welcome.vue").default
  'NuxtLayout': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-layout").default
  'NuxtErrorBoundary': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue").default
  'ClientOnly': typeof import("../../node_modules/nuxt/dist/app/components/client-only").default
  'DevOnly': typeof import("../../node_modules/nuxt/dist/app/components/dev-only").default
  'ServerPlaceholder': typeof import("../../node_modules/nuxt/dist/app/components/server-placeholder").default
  'NuxtLink': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-link").default
  'NuxtLoadingIndicator': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator").default
  'NuxtTime': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-time.vue").default
  'NuxtRouteAnnouncer': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-route-announcer").default
  'NuxtImg': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-stubs").NuxtImg
  'NuxtPicture': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-stubs").NuxtPicture
  'NuxtPage': typeof import("../../node_modules/nuxt/dist/pages/runtime/page").default
  'NoScript': typeof import("../../node_modules/nuxt/dist/head/runtime/components").NoScript
  'Link': typeof import("../../node_modules/nuxt/dist/head/runtime/components").Link
  'Base': typeof import("../../node_modules/nuxt/dist/head/runtime/components").Base
  'Title': typeof import("../../node_modules/nuxt/dist/head/runtime/components").Title
  'Meta': typeof import("../../node_modules/nuxt/dist/head/runtime/components").Meta
  'Style': typeof import("../../node_modules/nuxt/dist/head/runtime/components").Style
  'Head': typeof import("../../node_modules/nuxt/dist/head/runtime/components").Head
  'Html': typeof import("../../node_modules/nuxt/dist/head/runtime/components").Html
  'Body': typeof import("../../node_modules/nuxt/dist/head/runtime/components").Body
  'NuxtIsland': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-island").default
  'LazyAppFooter': LazyComponent<typeof import("../../components/AppFooter.vue").default>
  'LazyAppHeader': LazyComponent<typeof import("../../components/AppHeader.vue").default>
  'LazyAtomsActionButton': LazyComponent<typeof import("../../components/Atoms/ActionButton.vue").default>
  'LazyAtomsActionButtonD': LazyComponent<typeof import("../../components/Atoms/ActionButtonD.vue").default>
  'LazyAtomsActionButtonn': LazyComponent<typeof import("../../components/Atoms/ActionButtonn.vue").default>
  'LazyAtomsActionLinkButton': LazyComponent<typeof import("../../components/Atoms/ActionLinkButton.vue").default>
  'LazyAtomsAddToCartButton': LazyComponent<typeof import("../../components/Atoms/AddToCartButton.vue").default>
  'LazyAtomsAppLogo': LazyComponent<typeof import("../../components/Atoms/AppLogo.vue").default>
  'LazyAtomsBaseIcon': LazyComponent<typeof import("../../components/Atoms/BaseIcon.vue").default>
  'LazyAtomsBaseInput': LazyComponent<typeof import("../../components/Atoms/BaseInput.vue").default>
  'LazyAtomsButtonEtsy': LazyComponent<typeof import("../../components/Atoms/ButtonEtsy.vue").default>
  'LazyAtomsDividerLine': LazyComponent<typeof import("../../components/Atoms/DividerLine.vue").default>
  'LazyAtomsFormSelect': LazyComponent<typeof import("../../components/Atoms/FormSelect.vue").default>
  'LazyAtomsHeaderButton': LazyComponent<typeof import("../../components/Atoms/HeaderButton.vue").default>
  'LazyAtomsHeading': LazyComponent<typeof import("../../components/Atoms/Heading.vue").default>
  'LazyAtomsHeadingAdd': LazyComponent<typeof import("../../components/Atoms/HeadingAdd.vue").default>
  'LazyAtomsHeadingD': LazyComponent<typeof import("../../components/Atoms/HeadingD.vue").default>
  'LazyAtomsHeadingH': LazyComponent<typeof import("../../components/Atoms/HeadingH.vue").default>
  'LazyAtomsImage': LazyComponent<typeof import("../../components/Atoms/Image.vue").default>
  'LazyAtomsImageAtom': LazyComponent<typeof import("../../components/Atoms/ImageAtom.vue").default>
  'LazyAtomsImageAtomD': LazyComponent<typeof import("../../components/Atoms/ImageAtomD.vue").default>
  'LazyAtomsImageAtomH': LazyComponent<typeof import("../../components/Atoms/ImageAtomH.vue").default>
  'LazyAtomsImageAtomm': LazyComponent<typeof import("../../components/Atoms/ImageAtomm.vue").default>
  'LazyAtomsInputCheckbox': LazyComponent<typeof import("../../components/Atoms/InputCheckbox.vue").default>
  'LazyAtomsInputEmail': LazyComponent<typeof import("../../components/Atoms/InputEmail.vue").default>
  'LazyAtomsLabelApp': LazyComponent<typeof import("../../components/Atoms/LabelApp.vue").default>
  'LazyAtomsLabelLinkH': LazyComponent<typeof import("../../components/Atoms/LabelLinkH.vue").default>
  'LazyAtomsLinkMail': LazyComponent<typeof import("../../components/Atoms/LinkMail.vue").default>
  'LazyAtomsNavLink': LazyComponent<typeof import("../../components/Atoms/NavLink.vue").default>
  'LazyAtomsParagraphAdd': LazyComponent<typeof import("../../components/Atoms/ParagraphAdd.vue").default>
  'LazyAtomsParagraphD': LazyComponent<typeof import("../../components/Atoms/ParagraphD.vue").default>
  'LazyAtomsParagraphH': LazyComponent<typeof import("../../components/Atoms/ParagraphH.vue").default>
  'LazyAtomsPaymentCircle': LazyComponent<typeof import("../../components/Atoms/PaymentCircle.vue").default>
  'LazyAtomsPriceLabel': LazyComponent<typeof import("../../components/Atoms/PriceLabel.vue").default>
  'LazyAtomsPrimaryButton': LazyComponent<typeof import("../../components/Atoms/PrimaryButton.vue").default>
  'LazyAtomsPrimaryButtonn': LazyComponent<typeof import("../../components/Atoms/PrimaryButtonn.vue").default>
  'LazyAtomsProductImage': LazyComponent<typeof import("../../components/Atoms/ProductImage.vue").default>
  'LazyAtomsSearchInput': LazyComponent<typeof import("../../components/Atoms/SearchInput.vue").default>
  'LazyAtomsSectionTitle': LazyComponent<typeof import("../../components/Atoms/SectionTitle.vue").default>
  'LazyAtomsSocialIcon': LazyComponent<typeof import("../../components/Atoms/SocialIcon.vue").default>
  'LazyAtomsSocialImage': LazyComponent<typeof import("../../components/Atoms/SocialImage.vue").default>
  'LazyAtomsSocialImagee': LazyComponent<typeof import("../../components/Atoms/SocialImagee.vue").default>
  'LazyAtomsSpacerAdd': LazyComponent<typeof import("../../components/Atoms/SpacerAdd.vue").default>
  'LazyAtomsTextInputArea': LazyComponent<typeof import("../../components/Atoms/TextInputArea.vue").default>
  'LazyAtomsLogoMail': LazyComponent<typeof import("../../components/Atoms/logoMail.vue").default>
  'LazyHolidayCategoryGridView': LazyComponent<typeof import("../../components/HolidayCategoryGridView.vue").default>
  'LazyHolidayGiftSlider': LazyComponent<typeof import("../../components/HolidayGiftSlider.vue").default>
  'LazyHomePageCampaignsSection': LazyComponent<typeof import("../../components/HomePageCampaignsSection.vue").default>
  'LazyMoleculesAppDownloadSection': LazyComponent<typeof import("../../components/Molecules/AppDownloadSection.vue").default>
  'LazyMoleculesCampaignCard': LazyComponent<typeof import("../../components/Molecules/CampaignCard.vue").default>
  'LazyMoleculesCardInfo': LazyComponent<typeof import("../../components/Molecules/CardInfo.vue").default>
  'LazyMoleculesCategoryBox': LazyComponent<typeof import("../../components/Molecules/CategoryBox.vue").default>
  'LazyMoleculesCategoryCard': LazyComponent<typeof import("../../components/Molecules/CategoryCard.vue").default>
  'LazyMoleculesCouponSection': LazyComponent<typeof import("../../components/Molecules/CouponSection.vue").default>
  'LazyMoleculesDealBanner': LazyComponent<typeof import("../../components/Molecules/DealBanner.vue").default>
  'LazyMoleculesHousewarmingBanner': LazyComponent<typeof import("../../components/Molecules/HousewarmingBanner.vue").default>
  'LazyMoleculesHubTitleArea': LazyComponent<typeof import("../../components/Molecules/HubTitleArea.vue").default>
  'LazyMoleculesInputGroup': LazyComponent<typeof import("../../components/Molecules/InputGroup.vue").default>
  'LazyMoleculesInputGroupp': LazyComponent<typeof import("../../components/Molecules/InputGroupp.vue").default>
  'LazyMoleculesItemDetailRow': LazyComponent<typeof import("../../components/Molecules/ItemDetailRow.vue").default>
  'LazyMoleculesLinkColumn': LazyComponent<typeof import("../../components/Molecules/LinkColumn.vue").default>
  'LazyMoleculesNavLinkItem': LazyComponent<typeof import("../../components/Molecules/NavLinkItem.vue").default>
  'LazyMoleculesOptionGroup': LazyComponent<typeof import("../../components/Molecules/OptionGroup.vue").default>
  'LazyMoleculesOptionsRow': LazyComponent<typeof import("../../components/Molecules/OptionsRow.vue").default>
  'LazyMoleculesPaymentMethod': LazyComponent<typeof import("../../components/Molecules/PaymentMethod.vue").default>
  'LazyMoleculesPersonalization': LazyComponent<typeof import("../../components/Molecules/Personalization.vue").default>
  'LazyMoleculesPriceSection': LazyComponent<typeof import("../../components/Molecules/PriceSection.vue").default>
  'LazyMoleculesProductCard': LazyComponent<typeof import("../../components/Molecules/ProductCard.vue").default>
  'LazyMoleculesProductCardd': LazyComponent<typeof import("../../components/Molecules/ProductCardd.vue").default>
  'LazyMoleculesRenewableMessage': LazyComponent<typeof import("../../components/Molecules/RenewableMessage.vue").default>
  'LazyMoleculesSearchBar': LazyComponent<typeof import("../../components/Molecules/SearchBar.vue").default>
  'LazyMoleculesSellerBadge': LazyComponent<typeof import("../../components/Molecules/SellerBadge.vue").default>
  'LazyMoleculesSellerInfoRow': LazyComponent<typeof import("../../components/Molecules/SellerInfoRow.vue").default>
  'LazyMoleculesSellerRow': LazyComponent<typeof import("../../components/Molecules/SellerRow.vue").default>
  'LazyMoleculesSocialButton': LazyComponent<typeof import("../../components/Molecules/SocialButton.vue").default>
  'LazyMoleculesSocialButtonn': LazyComponent<typeof import("../../components/Molecules/SocialButtonn.vue").default>
  'LazyMoleculesSocialIcons': LazyComponent<typeof import("../../components/Molecules/SocialIcons.vue").default>
  'LazyMoleculesStaticHeader': LazyComponent<typeof import("../../components/Molecules/StaticHeader.vue").default>
  'LazyMoleculesSubscribeForm': LazyComponent<typeof import("../../components/Molecules/SubscribeForm.vue").default>
  'LazyMoleculesThumbnailItem': LazyComponent<typeof import("../../components/Molecules/ThumbnailItem.vue").default>
  'LazyMoleculesUserActions': LazyComponent<typeof import("../../components/Molecules/UserActions.vue").default>
  'LazyOrganismAuthModal': LazyComponent<typeof import("../../components/Organism/AuthModal.vue").default>
  'LazyOrganismBigDeals': LazyComponent<typeof import("../../components/Organism/BigDeals.vue").default>
  'LazyOrganismCampaignGridSection': LazyComponent<typeof import("../../components/Organism/CampaignGridSection.vue").default>
  'LazyOrganismCartFooter': LazyComponent<typeof import("../../components/Organism/CartFooter.vue").default>
  'LazyOrganismCartItemDetails': LazyComponent<typeof import("../../components/Organism/CartItemDetails.vue").default>
  'LazyOrganismCategoryGrid': LazyComponent<typeof import("../../components/Organism/CategoryGrid.vue").default>
  'LazyOrganismCategoryMenu': LazyComponent<typeof import("../../components/Organism/CategoryMenu.vue").default>
  'LazyOrganismCategorySliderSection': LazyComponent<typeof import("../../components/Organism/CategorySliderSection.vue").default>
  'LazyOrganismCheckoutModal': LazyComponent<typeof import("../../components/Organism/CheckoutModal.vue").default>
  'LazyOrganismCustomizableIdeas': LazyComponent<typeof import("../../components/Organism/CustomizableIdeas.vue").default>
  'LazyOrganismDaintySparkle': LazyComponent<typeof import("../../components/Organism/DaintySparkle.vue").default>
  'LazyOrganismDayDeals': LazyComponent<typeof import("../../components/Organism/DayDeals.vue").default>
  'LazyOrganismEnchantedGarden': LazyComponent<typeof import("../../components/Organism/EnchantedGarden.vue").default>
  'LazyOrganismFilterRow': LazyComponent<typeof import("../../components/Organism/FilterRow.vue").default>
  'LazyOrganismFilterSidebar': LazyComponent<typeof import("../../components/Organism/FilterSidebar.vue").default>
  'LazyOrganismHighOctaneStyle': LazyComponent<typeof import("../../components/Organism/HighOctaneStyle.vue").default>
  'LazyOrganismHolidayFinds': LazyComponent<typeof import("../../components/Organism/HolidayFinds.vue").default>
  'LazyOrganismHubHeader': LazyComponent<typeof import("../../components/Organism/HubHeader.vue").default>
  'LazyOrganismImageGallery': LazyComponent<typeof import("../../components/Organism/ImageGallery.vue").default>
  'LazyOrganismInspiredPicks': LazyComponent<typeof import("../../components/Organism/InspiredPicks.vue").default>
  'LazyOrganismItemDetails': LazyComponent<typeof import("../../components/Organism/ItemDetails.vue").default>
  'LazyOrganismJumpBackIn': LazyComponent<typeof import("../../components/Organism/JumpBackIn.vue").default>
  'LazyOrganismLoginForm': LazyComponent<typeof import("../../components/Organism/LoginForm.vue").default>
  'LazyOrganismMainFooter': LazyComponent<typeof import("../../components/Organism/MainFooter.vue").default>
  'LazyOrganismMeetYourSeller': LazyComponent<typeof import("../../components/Organism/MeetYourSeller.vue").default>
  'LazyOrganismNavigationLinks': LazyComponent<typeof import("../../components/Organism/NavigationLinks.vue").default>
  'LazyOrganismPaymentSummary': LazyComponent<typeof import("../../components/Organism/PaymentSummary.vue").default>
  'LazyOrganismProductActions': LazyComponent<typeof import("../../components/Organism/ProductActions.vue").default>
  'LazyOrganismProductSlider': LazyComponent<typeof import("../../components/Organism/ProductSlider.vue").default>
  'LazyOrganismProductSliderSection': LazyComponent<typeof import("../../components/Organism/ProductSliderSection.vue").default>
  'LazyOrganismRecentFinds': LazyComponent<typeof import("../../components/Organism/RecentFinds.vue").default>
  'LazyOrganismRegisterFormm': LazyComponent<typeof import("../../components/Organism/RegisterFormm.vue").default>
  'LazyOrganismRelatedSearches': LazyComponent<typeof import("../../components/Organism/RelatedSearches.vue").default>
  'LazyOrganismReviewsSection': LazyComponent<typeof import("../../components/Organism/ReviewsSection.vue").default>
  'LazyOrganismShippingPolicies': LazyComponent<typeof import("../../components/Organism/ShippingPolicies.vue").default>
  'LazyOrganismSideCartDrawer': LazyComponent<typeof import("../../components/Organism/SideCartDrawer.vue").default>
  'LazyOrganismSimilarProductsSection': LazyComponent<typeof import("../../components/Organism/SimilarProductsSection.vue").default>
  'LazyOrganismSpecialGifts': LazyComponent<typeof import("../../components/Organism/SpecialGifts.vue").default>
  'LazyOrganismStockingStuffers': LazyComponent<typeof import("../../components/Organism/StockingStuffers.vue").default>
  'LazyOrganismSubscriptionSection': LazyComponent<typeof import("../../components/Organism/SubscriptionSection.vue").default>
  'LazyOrganismTopBannerSection': LazyComponent<typeof import("../../components/Organism/TopBannerSection.vue").default>
  'LazyOrganismTopHeaderRow': LazyComponent<typeof import("../../components/Organism/TopHeaderRow.vue").default>
  'LazyProductDetailView': LazyComponent<typeof import("../../components/ProductDetailView.vue").default>
  'LazyRelatedProductSlider': LazyComponent<typeof import("../../components/RelatedProductSlider.vue").default>
  'LazyShoppingCart': LazyComponent<typeof import("../../components/ShoppingCart.vue").default>
  'LazyUserLoginForm': LazyComponent<typeof import("../../components/UserLoginForm.vue").default>
  'LazyUserRegisterForm': LazyComponent<typeof import("../../components/UserRegisterForm.vue").default>
  'LazyIconsIconCommunity': LazyComponent<typeof import("../../components/icons/IconCommunity.vue").default>
  'LazyIconsIconDocumentation': LazyComponent<typeof import("../../components/icons/IconDocumentation.vue").default>
  'LazyIconsIconEcosystem': LazyComponent<typeof import("../../components/icons/IconEcosystem.vue").default>
  'LazyIconsIconSupport': LazyComponent<typeof import("../../components/icons/IconSupport.vue").default>
  'LazyIconsIconTooling': LazyComponent<typeof import("../../components/icons/IconTooling.vue").default>
  'LazyNuxtWelcome': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/welcome.vue").default>
  'LazyNuxtLayout': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-layout").default>
  'LazyNuxtErrorBoundary': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue").default>
  'LazyClientOnly': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/client-only").default>
  'LazyDevOnly': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/dev-only").default>
  'LazyServerPlaceholder': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/server-placeholder").default>
  'LazyNuxtLink': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-link").default>
  'LazyNuxtLoadingIndicator': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator").default>
  'LazyNuxtTime': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-time.vue").default>
  'LazyNuxtRouteAnnouncer': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-route-announcer").default>
  'LazyNuxtImg': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-stubs").NuxtImg>
  'LazyNuxtPicture': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-stubs").NuxtPicture>
  'LazyNuxtPage': LazyComponent<typeof import("../../node_modules/nuxt/dist/pages/runtime/page").default>
  'LazyNoScript': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components").NoScript>
  'LazyLink': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components").Link>
  'LazyBase': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components").Base>
  'LazyTitle': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components").Title>
  'LazyMeta': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components").Meta>
  'LazyStyle': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components").Style>
  'LazyHead': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components").Head>
  'LazyHtml': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components").Html>
  'LazyBody': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components").Body>
  'LazyNuxtIsland': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-island").default>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export {}
